cache:
  directories:
    - "$HOME/.m2"

language: java

jdk:
  - oraclejdk8
  
services:
  - mysql
  - mongodb

before_script:
  - mysql -e "CREATE DATABASE tpa"

after_script:
  - mvn clean package
  - "./.utility/.coverage.sh"

env:
  global:
    secure: N54uHDoiYqTxCcwRcVoJDiFC3Luncq+U20e2fatJTfVe1YrHtXQY90N1rjb1jlc8t7kIcHUi29Cct+Rt7Be1iru6peXj0MLoEaTek3TSiFZaK7o5Rwfd0UY8Nx0biBdylYnccH4MfK4SCzmUuI7WFwTS0t/nO+Tb/wo1Tp5rZo0uqgvp/gWL7BbhLvEBBDo7eNI7jsFqFZVeklAV70Np6vsTg9YLw9DOU0JAEI0opDOdseIwtxGtBxXWUh4bizH2MtfhCHNyS401sacgA3pEfEIWFnk+wuk5/jP6whTaqc5PXlMx/msO9c8zzFY2FfJR7kwDWqFXjj9x5QyZE+/EULHG+GaKcSo4qc7SYXlTDvlim3CKCJHMatwKTV5QmJMpYNaUwhzjWwmcy+Gs90APUJLzO0ekyNnL02QNPsQq8ottL4b8wd5yy4IGXSBtTnJoBIcRBVYnB3SgNIJrPo1mxZh8obvVGaMKi0cgnW6fQQ3BPbiGpdD9Np20+S4MKuYINZ7264dzS8fA1h4nWgp4kTzPLU3mNMa4reNrgFmPqBwvQsES6Aok/HakuiWJ0xXP7yXWspYb3umFlyhfdxJFhPpkIH/6NUQ8vQhkwnsjd/NFf+uwKfqFmZ1R+vgperGeagcjlMK8de2xaWwx28BqxkEiSMXN2O5QWGAVlPgHJTA=
